menu title LicheeRV Nano variant select
default nano-e
timeout 100
prompt 1

label nano-we
    menu label LicheeRV Nano-WE (Ethernet + WiFi6/BT5 AIC8800)
    kernel /Image
    fdt /sg2002-licheerv-nano-we.dtb
    append root=/dev/mmcblk0p2 rw rootwait console=ttyS0,115200 earlycon

label nano-b
    menu label LicheeRV Nano-B (no network)
    kernel /Image
    fdt /sg2002-licheerv-nano-b.dtb
    append root=/dev/mmcblk0p2 rw rootwait console=ttyS0,115200 earlycon

label nano-e
    menu label LicheeRV Nano-E (Ethernet)
    kernel /Image
    fdt /sg2002-licheerv-nano-e.dtb
    append root=/dev/mmcblk0p2 rw rootwait console=ttyS0,115200 earlycon

label nano-w
    menu label LicheeRV Nano-W (WiFi6/BT5 AIC8800)
    kernel /Image
    fdt /sg2002-licheerv-nano-w.dtb
    append root=/dev/mmcblk0p2 rw rootwait console=ttyS0,115200 earlycon
